#!/bin/bash


#    Copyright (C) 2013 Javier García, Julio Alberto González

#    This file is part of Rpi-Face.
#    Rpi-Face is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Rpi-Face is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Rpi-Face.  If not, see <http://www.gnu.org/licenses/>.

FILE_ANALYSIS=/var/www/cgi-bin/data/analysis.t3

#Dado que los resultados se muestran a modo de una nota por palabra, este comando lo que hace es calcular la media de lo que hay en la segunda $
average=`awk '{if(NR>4) {sum+=$2; ++t}} END { print sum/t}' $FILE_ANALYSIS` 
echo $average >&2
/var/www/cgi-bin/move_face $average

