#!/bin/bash

#    Copyright (C) 2013 Javier García, Julio Alberto González

#    This file is part of Rpi-Face.
#    Rpi-Face is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Rpi-Face is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Rpi-Face.  If not, see <http://www.gnu.org/licenses/>.

PORT_OK=31416
PORT_KO=27183
EMO_OK=lm/words_ok.lm
EMO_KO=lm/words_ko.lm
FREELING_PORT=25513
FLAG_EMOTIONAL=

hlp() {
	echo "rpi-face-server: Servidor para el proyecto Rpi-Face."
	echo
	echo "Inicia los servidores de probabilidad y el servidor de acciones, que se encarga de controlar los movimientos de la cara y la reproducción de mensajes."
	echo
	echo "Opciones:"
	echo "-o words_ok: Archivo con lista de palabras positivas (por defecto, lm/words_ok.txt)."
	echo "-k words_ko: Archivo con lista de palabras negativas (por defecto, lm/words_ko.txt)."
	echo "-p freeling_port: Puerto del servidor Freeling (por defecto 31416)."
	echo "-x: Cierra cualquier otra instancia del programa que se esté ejecutando y sale."
	echo "-e: Utiliza voz emocional."
	echo "-h: Muestra esta ayuda."
}

# procesar opciones
while getopts :hO:K:o:k:p:xe option
do
	case "$option" in
		h) hlp
			exit 0
			;;
		O) if (test $OPTARG -gt -1 2>/dev/null) && (test $OPTARG -lt 65536 2>/dev/null); then
				PORT_OK=$OPTARG  # Puerto del servidor positivo
			else
				echo "rpi-face-server: error: El argumento de -n debe ser un número entre 0 y 65535." >&2
				exit 1 
			fi;;
		K) if (test $OPTARG -gt -1 2>/dev/null) && (test $OPTARG -lt 65536 2>/dev/null); then
				PORT_KO=$OPTARG  # Puerto del servidor negativo
			else
				echo "rpi-face-server: error: El argumento de -n debe ser un número entre 0 y 65535." >&2
				exit 1 
			fi;;
		o) EMO_OK=$OPTARG;;
		k) EMO_KO=$OPTARG;;
		p) FREELING_PORT=$OPTARG;;
		x) killall ngram;
			killall -SIGINT freeling_server;
			killall freeling_server;
			killall action_manager;
			killall rpi-face-server;
			exit 0;;
		e) FLAG_EMOTIONAL="-e";
			;;
		*) echo "rpi-face-server: error: Opción incorrecta." >&2
			exit 1;;  # Opción incorrecta
	esac
done
shift `expr $OPTIND - 1`  # Eliminación de opciones
if [ `pgrep -c ^rpi-face-server$` -gt 1 ]; then
	echo "rpi-face-server: error: El programa ya se está ejecutando. Cierre la otra instancia del programa o ejecute rpi-face-server con la opción -x para forzar su cierre." >&2;
	exit 1;
fi;
# Iniciar servidores de probabilidad
ngram -lm "$EMO_OK" -server-port "$PORT_OK" > /dev/null 2> /dev/null &
ngram -lm "$EMO_KO" -server-port "$PORT_KO" > /dev/null 2> /dev/null &
# Iniciar Freeling
./freeling_server -p "$FREELING_PORT" >/dev/null &
# Iniciar servidor de acciones
./action_manager -o "$PORT_OK" -k "$PORT_KO" -p "$FREELING_PORT" "$FLAG_EMOTIONAL"
# Cerrar servidores de probabilidad cuando se salga de action_manager
killall -SIGINT freeling_server
killall freeling_server;
killall ngram