#!/bin/bash

#    Copyright (C) 2013 Javier García, Julio Alberto González

#    This file is part of Rpi-Face.
#    Rpi-Face is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Rpi-Face is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Rpi-Face.  If not, see <http://www.gnu.org/licenses/>.


#echo "calculando nota<br>"

# Direccion raiz de los binarios de ACOPOST
DIR_ACO=/var/www/cgi-bin/acopost
FILE_MESSAGE=/var/www/cgi-bin/data/fichero.raw
FILE_ANALYSIS=/var/www/cgi-bin/data/analysis.t3
T3=$DIR_ACO/acopost-1.8.6/bin/t3
MOVE_FACE=/var/www/cgi-bin/move_face


#Definición de variables.
sum=0
t=1

#Fichero en los que se encuentran los trigramas.
#NGRAM_EMO=$DIR_ACO/FINALEMO.123
NGRAM_EMO="demo/FINALEMO.123"
#Fichero en el que se encuentra el diccionario con las notas correspondientes a cada palabra.
#LEX_EMO=$DIR_ACO/FINALEMO.lex
LEX_EMO="demo/train.lex"

#Llamada al programa T3 de la libreria ACOPOST que realiza el etiquetado.
$T3 $NGRAM_EMO $LEX_EMO $FILE_MESSAGE $FILE_ANALYSIS
 

#Dado que los resultados se muestran a modo de una nota por palabra, este comando lo que hace es calcular la media de lo que hay en la segunda columna de texto de el archivo que te devuelve el etiquetador, es decir, la media de la nota de las palabras.  
# average=`awk '{if(NR>4) {sum+=$2; ++t}} END { print sum/t}' $FILE_ANALYSIS` 
# echo $average >&2
# $MOVE_FACE $average
